# Generated by Django 4.0.4 on 2026-04-21 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports01', '0019_alter_incident_data_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident_data',
            name='Attachment',
            field=models.FileField(blank=True, null=True, upload_to='incident_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
